//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-15 17:59:06 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace WebSiteCMS.Model
{
    /// <summary>
    /// 数据表实体类：ChannelInfoEntity 
    /// </summary>
    [Serializable()]
    public partial class ChannelInfoEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ChannelInfoId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ChanneKey { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LanguageKey { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ChannelUrl { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SortDesc { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ChanneImg { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TargetType { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? SortNum { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Name { get; set; }

           
    }    
}
	