//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-15 17:59:07 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace WebSiteCMS.Model
{
    /// <summary>
    /// 数据表实体类：HotelResourceEntity 
    /// </summary>
    [Serializable()]
    public partial class HotelResourceEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string HotelResourceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LanguageKey { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string FaceImage { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Title { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SortDesc { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string Content { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

           
    }    
}
	