//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-15 17:59:07 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace WebSiteCMS.Model
{
    /// <summary>
    /// 数据表实体类：SiteEntity 
    /// </summary>
    [Serializable()]
    public partial class SiteEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SiteId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LanguageKey { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CompanyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back1 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back2 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back3 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back4 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back5 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back6 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back7 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back8 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back9 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back10 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Back11 { get; set; }

           
    }    
}
	